name: Update Algolia with secret
on:
  push:
    branches:
      - main
jobs:
  update-algolia:
    name: Check for projects.csv updates and add records to Algolia
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: python -m pip install --upgrade pip algoliasearch jproperties
    
    - name: Test secret
      run: |
        if [ "$KEY" == "4187fadce79096b59dfd5c1df792754f" ] 
        then 
          echo "Got secret"
        else
          echo "Erro getting secret"  
        fi
        else  
      env: 
        KEY: ${{ secrets.KEY }}  
    - name: Run algolia.py
      run: python algolia.py
      env:
        KEY: ${{ secrets.KEY }}
      
